### use account
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}

### use account2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000000",
  "amount": 100
}


### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "ac0be46718c248ccb4f49bcc65ae27de",
  "accountNumber": "1000000000",
  "amount": 100
}

### query transaction
GET http://localhost:8080/transaction/d1633258dbb742fc98326ce932588325